services:
  scheduler:
    dns: [8.8.8.8, 1.1.1.1]
    extra_hosts:
      - "api.open-meteo.com:104.21.64.1"
  dag-processor:
    dns: [8.8.8.8, 1.1.1.1]
    extra_hosts:
      - "api.open-meteo.com:104.21.64.1"
  api-server:
    dns: [8.8.8.8, 1.1.1.1]
    extra_hosts:
      - "api.open-meteo.com:104.21.64.1"
  triggerer:
    dns: [8.8.8.8, 1.1.1.1]
    extra_hosts:
      - "api.open-meteo.com:104.21.64.1"